"use strict";

const STATUS = Object.freeze({
  STARTING: "STARTING",
  STOPPING: "STOPPING",
  RESTARTING: "RESTARTING",
  STOPPED: "STOPPED",
  CRASHED: "CRASHED",
  MINING: "MINING",
  CONNECTED: "CONNECTED",
  WAITING: "WAITING",
  DISCONNECTED: "DISCONNECTED"
});

const LOG = Object.freeze({
  INFO: "info",
  WARN: "warn",
  ERROR: "error",
  SUCCESS: "success",
  ACCENT: "accent",
  SYSTEM: "system"
});

const LIMITS = Object.freeze({
  MAX_SSE_CLIENTS: 4,

  BROADCAST_MS: 50,

  HEARTBEAT_MS: 15000,

  SESSION_TTL_MS: 1800 * 1000,

  REPLAY_LINES: 25,

  STREAM_BUFFER_BYTES: 65536,

  ACTION_DELAY_MS: 2000,

  PROBE_TIMEOUT_MS: 8000,

  FORCE_KILL_MS: 2000,

  STOP_TIMEOUT_MS: 10000,

  RESTART_GAP_MS: 500,

  SHUTDOWN_TIMEOUT_MS: 12000,

  GPU_FAILURE_BACKOFF_AFTER: 3,

  GPU_BACKOFF_MAX_MS: 120000,

  GPU_MAX_BUFFER_BYTES: 262144,

  SSE_MAX_BLOCKED_TICKS: 5
});

module.exports = { STATUS, LOG, LIMITS };
